# ===============================
# = SERVER
# ===============================
server.port=${PORT:8080}

# ===============================
# = DATA SOURCE
# ===============================
spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# = JPA / HIBERNATE
# ===============================
# 'update' cria as tabelas se elas nao existirem no banco do Railway
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# ===============================
# = FLYWAY
# ===============================
# Force o Flyway a ignorar os placeholders ${...}
spring.flyway.placeholder-replacement=false

# ===============================
# = Swagger/OpenAPI
# ===============================
# Desabilita o Swagger/OpenAPI em producao por seguranca
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

# ===============================
# = JWT
# ===============================
security.api.token.secret=${JWT_SECRET}